name: TranxCraft
main: com.wickedgaminguk.tranxcraft.TranxCraft
version: 1.0
authors: [WickedGamingUK]
description: The custom developed plugin for TranxCraft.
website: https://www.tranxcraft.com/
commands:
    admin:
        usage: /<command> <add|set|remove|info|list> <player> <rank>
        description: Admin management.
    ban:
        usage: /<command> <player> <reason>
        description: Ban management.
    commandviewer:
        usage: /<command>
        description: Toggles Command Viewer.
    info:
        usage: /<command> <player>
        description: Shows information about a player.
    o:
        usage: /<command> <message>
        description: Sends a message in AdminChat or toggles it.
    report:
        usage: /<command> <player> <message>
        description: Report a player.
    setloginmessage:
        usage: /<command> <message>
        description: Sets your login message.
    tranxcraft:
        usage: /<command>
        description: Displays useful information about TranxCraft.
        aliases: [tc]
    unban:
        usage: /<command> <player>
        description: Unbans a player.
    warn:
        usage: /<command> <player> <reason>
        description: Warn a player.
    namehistory:
        usage: /<command> <player>
        description: Shows the name history of a player.
    warp:
        usage: /<command> <warp>
        description: Warps to a pre-defined place.
    setwarp:
        usage: /<command> <warp>
        description: Set's a warp point.
    delwarp:
        usage: /<command> <warp>
        description: Deletes a warp.
    warplist:
        usage: /<command>
        description: Lists all available warps.
    pwarp:
        usage: /<command> <warp>
        description: Warps to a personally pre-defined place.
    psetwarp:
        usage: /<command> <warp>
        description: Set's a personal warp point.
    pdelwarp:
        usage: /<command> <warp>
        description: Deletes a personal warp.
    pwarplist:
        usage: /<command>
        description: Lists all available personal warps.
    announcement:
        usage: /<command> <add|set|remove|info|list>
        description: Announcement management.
    eco:
        usage: /<command> <give|set|reset>
        description: Economy management.

