name: TranxCraft
main: com.wickedgaminguk.tranxcraft.TranxCraft
version: 1.0
authors: [WickedGamingUK]
description: The custom developed plugin for TranxCraft.
website: https://www.tranxcraft.com/
commands:
    admin:
        usage: /<command> <add|set|remove|info|list> <player>
        description: Admin management.
    information:
        usage: /<command>
        description: Find information about the plugin and server
    ban:
        usage: /<command> <player> <reason>
        description: Ban management.
    commandviewer:
        usage: /<command>
        description: Toggles Command Viewer.
    info:
        usage: /<command> <player>
        description: Shows information about a player.
    o:
        usage: /<command> <message>
        description: Sends a message in AdminChat or toggles it.
    report:
        usage: /<command> <player> <message>
        description: Report a player.
    setloginmessage:
        usage: /<command> <message>
        description: Sets your login message.
    tranxcraft:
        usage: /<command>
        description: Displays useful information about TranxCraft.
        aliases: [tc]
    unban:
        usage: /<command> <player>
        description: Unbans a player.
    warn:
        usage: /<command> <player> <reason>
        description: Warn a player.
